local function load_menu(self)
	msg.post("go#mainmenu", "load")
	msg.post("go#mainmenu", "enable")
end
local function unload_menu(self)
	msg.post("go#mainmenu","unload")
end
local function load_main(self)
	msg.post("go#Level_1", "load")
	msg.post("go#Level_1", "enable")
end
function init(self)
	msg.post(".", "acquire_input_focus")
	load_menu(self)
end
function on_message(self, message_id, message, sender)
	if message_id == hash("start_game") then
		unload_menu(self)
		load_main(self)
	end
end